name: Demo deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Prepare
      working-directory: .
      run: |
        npm install
        npm run build
        cd example && npm install
        
    - name: Deploy with gh-pages
      working-directory: ./example
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        npm run deploy -- -u "bit-about <bot@bit-about.tools>"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
