name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Prepare
      run: |
        npm install

    - name: Test
      run: |
        npm run test
        
    - name: Codecov
      uses: codecov/codecov-action@v2.1.0
      with:
        directory: coverage
